### ISSUE TITLE
Animation completion handler

### ISSUE THREAD

**Issue by jordaneckhardt** [wajahatkarim3/EasyFlipView#11]
Are you expecting to provide a way for users to set an animation completion handler? We can already get the duration of the animation, so we could just use a timer, but if the API is already doing something when the animation completes, it would be good to ensure that the user's completion tasks would be done after the API's.

**Comment by wajahatkarim3** [comment]
Yes, I have some features in my mind. One of those includes the `OnFlippedListener`. It might take few days to finish it and make it available on jCenter() due to my hectic schedule. But you can create PR if you have implemented it. Thanks

**Comment by jordaneckhardt** [comment]
Okay, perfect. Thanks!

**Comment by wajahatkarim3** [comment]
Hello @jordaneckhardt 
I have added the Animation Listener in the latest release 2.0.2 of EasyFlipView. Please check it. Thanks
