### ISSUE TITLE
Flipping the layout manually

### ISSUE THREAD

**Issue by emreakcan** [wajahatkarim3/EasyFlipView#15]
i want to do manual flip i mean card must follow the finger not automatically flip how can i do?  did anyone do it?

**Comment by Jakester0813** [comment]
Look up how to implement swipe listener gesture on Android. Once you got that down and able to trigger swipe calls, just call 'mYourFlipView.flipTheView()' to flip the view

**Comment by wajahatkarim3** [comment]
@emreakcan I know its very late. But, finally I managed to create manual flipping and created a new library called as [`EasyFlipViewPager`](https://github.com/wajahatkarim3/EasyFlipViewPager). You can check the [Poker Card Demo](https://github.com/wajahatkarim3/EasyFlipViewPager/blob/master/app/src/main/java/com/wajahatkarim3/easyflipviewpager/demo/PokerCardDemoActivity.java) to see how you can achieve manual flipping with that library 😄
