### ISSUE TITLE
Help please! i need to save the instance of side to SharedPreferences. how can i do this?

### ISSUE THREAD

**Issue by karbyshevden** [wajahatkarim3/EasyFlipView#16]
I want to save the side of card to SharedPreferences, and open the correct side after pause or closing the app. (I work with onPause and onResume methods).

**Comment by wajahatkarim3** [comment]
You can do it very easily through `Flip Animation Listener`. You can store any boolean based on the `newCurrentSide` parameter in the flip animation listener and loading it in onPause() and flipping the view accordingly. 

You can learn about flip animation listener at: https://github.com/wajahatkarim3/EasyFlipView#flip-animation-listener
