### ISSUE TITLE
change flip mode in recyclerview

### ISSUE THREAD

**Issue by duz17** [wajahatkarim3/EasyFlipView#17]
when I use flipview inside recyclerview some bugs happen
when scrolling, reused view that I need to change from back to front (or opposite), I tried to use flipTheView method withAnimate=false - but the result is seeing the back for second and then the front
I tried to use setFlipDuration(0) before, but the result of that is the animation stays with duration 0 for every next flipTheView call withAnimation=true

**Comment by wajahatkarim3** [comment]
We have already compiled a demo of recyclerview with flipview in each item. Can you check whether that works for you or not?  Let me know so that i can work accordingly.
