### ISSUE TITLE
Unable to scroll EasyFlipView 

### ISSUE THREAD

**Issue by jazzbpn** [wajahatkarim3/EasyFlipView#19]
Scrolling issue while trying to scroll the items of recycler view. Unable to scroll while clicking EasyFlipView ITEM_VIEW. And if we tried to scroll with other views rather than  EasyFlipViewview is scrolling only in that case.

**Comment by sachinvarma** [comment]
Please go through the example thoroughly, An working example is already given. Please don't forgot to add  **app:flipOnTouch="false"** on the item layout of your recyclerview. Hope it will solve your issue.

**Comment by ajinkya976** [comment]
performed app:flipOnTouch="false step and added onclick listener as mentioned.

but when i am clicking on the image it not flips only scrolling is working.

please help on above.

or if there is an alternative to scroll functionality (without recyclerview) with flip then please let me know.

for now i can either scroll or flip both i cant do. please help.
