### ISSUE TITLE
quick click

### ISSUE THREAD

**Issue by ONARAINYDAY** [wajahatkarim3/EasyFlipView#2]
fast click on a bug ,recommend filtering out fast click

                                          -- English come from google translate.

**Comment by wajahatkarim3** [comment]
Can you please explain it in more details. Thanks

**Comment by ONARAINYDAY** [comment]
抱歉，是有一个问题，不是b..用词不当了。
在demo中：
不能发图给你，简单描述一下，快速点击银行卡，银行卡会处会显示空白。
快速点击第二张图，也会有一点小问题。

**Comment by wajahatkarim3** [comment]
I have translated your query in English and i am still unable to understand your problem.

**Comment by ONARAINYDAY** [comment]
i'm sorry , i don't see your information.
i say, quick click one picture, The display does not appear.
quick click two pic, send your email.

**Comment by wajahatkarim3** [comment]
So demo apk doesn't work on your device? is that what you are saying?

**Comment by wajahatkarim3** [comment]
Okay... I got your email. Looks like card back side image resolution is high. And its not loading on the device. You can add any other low-size image or any custom layout as described in the documentation and test on that as well

**Comment by ONARAINYDAY** [comment]
Work no problem, the mailbox has been sent, you go and see.
The result of  Multiple quick clicks.

**Comment by wajahatkarim3** [comment]
Okay I got it. Multiple quick clicks are creating weird behavior. I will fix that today... Thanks.

**Comment by wajahatkarim3** [comment]
Fixed issue in v1.0.1.
