### ISSUE TITLE
Artifacts appearing on flipping

### ISSUE THREAD

**Issue by ljaniszewski** [wajahatkarim3/EasyFlipView#21]
The best to see for yourself 
https://youtu.be/CSgVNxgrKIY

the code:

```
<?xml version="1.0" encoding="utf-8"?>
<com.wajahatkarim3.easyflipview.EasyFlipView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/flipper"
    android:layout_width="match_parent"
    android:layout_height="200dp"
    app:flipOnTouch="true"
    app:flipEnabled="true"
    app:flipDuration="400"
    app:flipType="horizontal"
    >

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="16dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Front"
            android:textAppearance="@style/TextAppearance.AppCompat.Large" />

    </android.support.v7.widget.CardView>

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="16dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="@style/TextAppearance.AppCompat.Large"
            android:text="Back"/>

    </android.support.v7.widget.CardView>

</com.wajahatkarim3.easyflipview.EasyFlipView>
```

Any idea why this is happening/what I'm doing wrong?

**Comment by wajahatkarim3** [comment]
I think its happening due to ```CardView```'s drop shadow. I would have to look at it.

**Comment by ljaniszewski** [comment]
Thanks man, I just done exactly the thing haha.
I set elevation to 0dp and it's fixed. But CardView without elevation is like a dog without a bone! haha

**Comment by wajahatkarim3** [comment]
I see. I just looked at the demo app, and i realized that the first demo i created for EasyFlipView was using ```CardView```. Here is the link to the front side layout: https://github.com/wajahatkarim3/EasyFlipView/blob/master/app/src/main/res/layout/flash_card_layout_back.xml

I think you have increased the initial elevation or something. Because the flipping in the demo looks good.

**Comment by ljaniszewski** [comment]
No, elevation is standard. So this layout is basically the same, only uses <include> tags instead normal nesting. I am going to try use this that way, but I suspect there would be no difference. 
The phone is Nexus 5, I will try and test this on other phones in a minute.

**Comment by wajahatkarim3** [comment]
Yeah Sure. Do let me know 👍

**Comment by ljaniszewski** [comment]
Testes on Huawei p8, Samsung s5, and LG g3 additionally, and the effect is the same, though on LG g3 there is another weird thing going on - the card doesn't flip on touch most of the times https://youtu.be/o4jtiOZVVJ0 

Is there demo .apk available somewhere?

**Comment by wajahatkarim3** [comment]
Yes. You can get the APK at https://github.com/wajahatkarim3/EasyFlipView/releases/download/1.0.0/EasyFlipView-Demo_v1.0.0.apk
