### ISSUE TITLE
If Keyboard appears on top of Flip view and then closed, Flip view is not visible after that.

### ISSUE THREAD

**Issue by gssirohi** [wajahatkarim3/EasyFlipView#22]
If Keyboard appears on top of Flip view and then closed, Flip view is not visible after that. It reappears if touched on the placeholder

**Comment by wajahatkarim3** [comment]
Thank you for using EasyFlipView. Looks like any bug. I will check it later tonight and see what's the issue?

Can you please share any GIF etc. so that I can understand it more clearly?

Thanks
