### ISSUE TITLE
NuGet 

### ISSUE THREAD

**Issue by mrhamok** [wajahatkarim3/EasyFlipView#26]
Hello,

how resolve this error ?

Package EasyFlipView 1.0.0 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package EasyFlipView 1.0.0 supports: net (.NETFramework,Version=v0.0)

regards

**Comment by wajahatkarim3** [comment]
Well, this library is for Android native development. So, it won't be possible in MonoAndroid or any other framework for this.
