### ISSUE TITLE
View clipping

### ISSUE THREAD

**Issue by AdityaAnand1** [wajahatkarim3/EasyFlipView#4]
There's some noticeable clipping near the corners even in the preview gif itself:

![image](https://raw.githubusercontent.com/wajahatkarim3/EasyFlipView/master/Art/demo.gif)

I was wondering if there's a workaround to let the view overflow it's bounds, i.e., draw over other elements if needed to make the whole animation visible.

**Comment by wajahatkarim3** [comment]
That's good catch. At this moment, I haven't thought about it but will look into in later.
