### ISSUE TITLE
How to flip inside listview?

### ISSUE THREAD

**Issue by Vhox** [wajahatkarim3/EasyFlipView#41]
Hello folks and Mr. Karim.

I am trying to do the easyflip manually, because I am using a List View, but with no success...
When I do the touch, the app closes...

Here is my code, if someone could help me I aprecciate:

`
public class Main5Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main5);

        //reads a txt file and create a list view with its content
        readTxt();

        //trying to make a easyflip manually, but I failed... When I click the item on list view, the app closes
        ListView list = (ListView) findViewById(R.id.list_cards);

        final EasyFlipView efView = (EasyFlipView) findViewById(R.id.cardflip);

        list.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                try {

                    efView.flipTheView();

                }

                catch (Exception e) {

                    Toast.makeText(getApplicationContext(), (CharSequence) e, Toast.LENGTH_LONG).show();

                }

            }
        });

    public void readTxt () {

        File caminhoTxt = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS) + "/lookupgs1.txt");

        if (caminhoTxt.exists()) {

            try {

                String line;

                FileReader fileReader2 = new FileReader(caminhoTxt);
                BufferedReader buffer = new BufferedReader(fileReader2);
                CardAdapter adapter = new CardAdapter(this);

                while ((line = buffer.readLine()) != null) {

                    String[] parametros = line.split(";");

                    String codRFID = parametros[0];
                    String desc = parametros[1];

                    ListView lvCards = (ListView) findViewById(R.id.list_cards);

                    lvCards.setAdapter(adapter);

                    try {

                        if (desc.contains("Controlador")) {

                            adapter.add(new CardModel(R.drawable.quadro, desc, codRFID));

                        }

                        else if (desc.contains("Quadro")) {

                            adapter.add(new CardModel(R.drawable.quadro, desc, codRFID));

                        }

                        else if (desc.contains("Medicamentos")) {

                            adapter.add(new CardModel(R.drawable.med, desc, codRFID));

                        }

                        else if (desc.contains("Câmera de Validação Esteira")) {

                            adapter.add(new CardModel(R.drawable.quadro, desc, codRFID));

                        }

                        else if (desc.contains("Impressora")) {

                            adapter.add(new CardModel(R.drawable.printer01, desc, codRFID));

                        }

                        else {

                            adapter.add(new CardModel(R.drawable.cpx, desc, codRFID));

                        }

                    }

                    catch (Exception e) {

                        Toast.makeText(this, (CharSequence) e, Toast.LENGTH_LONG).show();
                    }

                }

            }

            catch (Exception e) {

                Toast.makeText(this, (CharSequence) e, Toast.LENGTH_SHORT).show();

            }
        }

        else {

            Toast.makeText(this, "File \"lookupgs1.txt\" Not Founded!", Toast.LENGTH_SHORT).show();

        }
    }

}
`

**Comment by wajahatkarim3** [comment]
I don't have full context of your issue in terms of code. But from what I understand from your code is that you have a list of cards. And you want to flip each on click. But, in your `onItemClick()` method, you are calling the `efView.flipTheView()`. I believe your `efView` is null here, because you can't access the views of the list directly in `onCreate()`. You need to create an adapter and add click listener and flipping the view call there. Not in `onCreate()` or `Activity` class. Hope it helps.
