### ISSUE TITLE
front views can be seen reversed for a short delay at the end of the animation

### ISSUE THREAD

**Issue by maaks** [wajahatkarim3/EasyFlipView#44]
When I flip my component, at the end of the animation I can see through the back view for a short time. what I see is, for example, the text view of the front view reversed. It doesn't matter if I set a background to the view or not.

EDIT: I tested to put a very long animation time to see what happens.
It works well but at the end of the animation there is a flickering showing the front view flipped then the back view again (like if the back view disappeared for a short time)

Any clues?
Cheers!

**Comment by wajahatkarim3** [comment]
Thank you for letting me know this. I will look into it and release an update for this. Thanks

**Comment by wajahatkarim3** [comment]
I looked into this and debugged but haven't been able to reproduce this. I am releasing a new version of the library today `3.0.0` with support of Android X . Hopefully, this issue won't happen again. Thanks for your feedback.
