### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by wajahatkarim3** [wajahatkarim3/EasyFlipView#52]
JFrog just announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:
* February 28th: No more submissions will be accepted to Bintray, JCenter
* May 1st: Bintray, JCenter services will no longer be available

Hence this library should also be migrated to another maven repository like Maven central.

**Comment by makks129** [comment]
Hey @wajahatkarim3, has anything been done with this issue? I cannot use your lib anymore because it's on JCenter

**Comment by dalpissollaura** [comment]
any updates???

**Comment by wajahatkarim3** [comment]
@makks129 , @lewisjwilson , @dalpissollaura You can use the library using the following Gradle depenency from MavenCentral now.

```groovy
implementation 'com.wajahatkarim:EasyFlipView:3.0.3'
```
