### ISSUE TITLE
Build fails due to EasyFlipView dependency issue

### ISSUE THREAD

**Issue by tartarJR** [wajahatkarim3/EasyFlipView#57]
My builds started failing today for some reason and I am getting this message

`Could not determine artifacts for com.wajahatkarim3.EasyFlipView:EasyFlipView:2.1.2: Skipped due to earlier error`

Any ideas about how to fix that?

**Comment by wajahatkarim3** [comment]
@tartarJR You can use the library using the following Gradle depenency from MavenCentral now.

```groovy
implementation 'com.wajahatkarim:EasyFlipView:3.0.3'
```
