### ISSUE TITLE
Animation not working without click

### ISSUE THREAD

**Issue by omerates760** [wajahatkarim3/EasyFlipView#59]
I want to convert animation to frontend programmatically. I guess this library doesn't support this feature.

**Comment by wajahatkarim3** [comment]
You can trigger the flip animation from the code anywhere using these methods 

```kotlin
// Flips the view with or without animation
yourFlipView.flipTheView();
yourFlipView.flipTheView(false);
```

The `boolean` parameter tells if the animation should be played or not.
