### ISSUE TITLE
backside  unclickable

### ISSUE THREAD

**Issue by guangit** [wajahatkarim3/EasyFlipView#6]
I want to add click things(not flip ,such as jump to ...) in backside . It does not work!
(我想在背面的view 添加点击事件 ， 但是不能生效)

**Comment by wajahatkarim3** [comment]
You can do it by setting flipOnTouch to false like this:
```xml
app:flipOnTouch="true"
``` 
or in Java like 
```java
mYourFlipView.setFlipOntouch(false);
```

Be default, flipOnTouch is set to true. If you set it to false, then it won't flip. Rather, you will have to flip the card manually in java on any click or any button or wherever you want like this:
```java
// Flips the view with animation
mYourFlipView.flipTheView();
// Flips the view without animation
mYourFlipView.flipTheView(false);
```

**Comment by guangit** [comment]
原谅我使用中文了，我用英文描述不清。
我的需求是这样的，我想给背面的view 设置点击事件 用来执行别的操作，而不是旋转整个view.

**Comment by wajahatkarim3** [comment]
No Problem. 
Here is the way you can do it:
First in XML, set ```android:flipOnTouch="false" ``` for your FlipView. Then all the buttons in your views will be clickable.

**Comment by guangit** [comment]
这样在背面是可以点击，但是获得焦点的是 正面的view

**Comment by wajahatkarim3** [comment]
Both sides are clickable. If you want to flip the view now, you can do it by calling ```mYourFlipView.flipTheView();``` from java code on any click event.

**Comment by guangit** [comment]
please check your gmail ,  thanks.      wajahatkarim3@gmail.com
