### ISSUE TITLE
Flip directions

### ISSUE THREAD

**Issue by webserveis** [wajahatkarim3/EasyFlipView#60]
How to set flip and back flip inverse?

click
left to right

click
right to left

**Comment by wajahatkarim3** [comment]
You can change the directions either through code 

![image](https://github.com/wajahatkarim3/EasyFlipView/assets/8867121/36cc5c53-79df-4a60-856f-0e04a6f84781)

or with XML like 

![image](https://github.com/wajahatkarim3/EasyFlipView/assets/8867121/0a3ff92a-3f65-4d18-98de-7a87988c385c)
