### ISSUE TITLE
Clipping

### ISSUE THREAD

**Issue by ueen** [wajahatkarim3/EasyFlipView#64]
Hey, the front/back views are clipped at the top and bottom at the EasyFlipView bounds while flipping (horizontal).
Is there way to fix this? I tried

```
android:clipChildren="false"
android:clipToPadding="false"
```

on the FlipView to no avail.

**Comment by ueen** [comment]
Just got it:
`android:clipChildren="false"` needs to be added to the parent/root view
and
`android:clipToPadding="false"` to the FlipView

maybe this could be added to the README :)

**Comment by wajahatkarim3** [comment]
Thank you. Added this in ReadMe

![image](https://github.com/user-attachments/assets/0b47499e-c1ec-4a01-ad54-f291a854b85a)
