### ISSUE TITLE
Question: Reverse the flipping direction?

### ISSUE THREAD

**Issue by NightSkyDev** [wajahatkarim3/EasyFlipView#7]
Hi,

Thanks for making your library available!  It's very much appreciated and is working great.

I appreciate it really is an "easy" library too :)

The one question I have is: is it possible to reverse the flipping direction?  It would be nice to reverse flip when going from the back to the front.  

Thanks!

**Comment by wajahatkarim3** [comment]
At this moment, it doesn't support custom animations. I am working on an update to add custom animations and more directions (such as up, down, etc). Will let you know as it gets available on jcenter(). Thanks
