### ISSUE TITLE
When adding multiple view with scrollview,it cant be scrollable.

### ISSUE THREAD

**Issue by FajarKhan** [wajahatkarim3/EasyFlipView#8]

**Comment by wajahatkarim3** [comment]
Well, that's because you might have 
```xml
app:flipOnTouch="true"
```
enabled in your xml layouts. Set this ```flipOnTouch``` attribute to false, and then your views will be scrollable. But then you will have to flip it yourself on any button click etc.

**Comment by FajarKhan** [comment]
yes I have app:flipOnTouch="true" in XML . so I just remove it in each view then do it programically? I want to flip when user click on it as well as it should be scrollable? This is possible?

**Comment by wajahatkarim3** [comment]
Yes. It could be possible. You have to add touch event listener and manually detect the difference in scrolling and touching, and programmatically flipping the view.
