### ISSUE TITLE
Creating the view programmatically

### ISSUE THREAD

**Issue by iGio90** [wajahatkarim3/EasyFlipView#9]
Hello, your code assume that the EasyFlipView is inflated from an xml layout. Building it programmatically will generate an NPE I.E here:

```
    public void setFlipDuration(int flipDuration) {
        this.flipDuration = flipDuration;
        ((Animator)this.mSetRightOut.getChildAnimations().get(0)).setDuration((long)flipDuration);
        ((Animator)this.mSetRightOut.getChildAnimations().get(1)).setStartDelay((long)(flipDuration / 2));
        ((Animator)this.mSetLeftIn.getChildAnimations().get(1)).setDuration((long)flipDuration);
        ((Animator)this.mSetLeftIn.getChildAnimations().get(2)).setStartDelay((long)(flipDuration / 2));
    }
```

because mSetRightOut will always be null as it is built in the "OnFinishInflate", which is not callable from outside and called only if the view is inflated from an XML layout

I would suggest to simply add a method (public) called setup() that is fired as well in OnFinishInflate but could allow people to build the view programmatically and setup later as needed. 

Thanks!

**Comment by wajahatkarim3** [comment]
Hello Thank you for your feedback. This feature of inflating dynamic layouts at runtime in flipview is already in pipeline of next feature. If you can contribute, then I can accept your pull request :) 

Thanks

**Comment by iGio90** [comment]
Yes!! Ive almost wrapped out all your class because i need to add and remove views into the flipper in runtime so i added many check on null childs. What i did in the end for this purpose is to override all addview methods and call your findView after the super.addView. I can pr this later this night :)

**Comment by wajahatkarim3** [comment]
That sounds great! I will be looking forward to it then :)
